CREATE DATABASE alunos
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE alunos;
CREATE TABLE aluno(
	id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(30) NOT NULL,
	telefone VARCHAR(14)/*BIGINT*/,
    email VARCHAR(100),
    cpf VARCHAR(11) NOT NULL,
    PRIMARY KEY(id)
)DEFAULT CHARSET=utf8mb4;

